const INFO_DEFAULT = {
  id: 0,
  title: '',
  thumbnail: 'https://media.tenor.com/wpSo-8CrXqUAAAAm/loading-loading-forever.webp',
  short_description: '',
  game_url: '',
  genre: '',
  platform: '',
  publisher: '',
  developer: '',
  release_date: '',
  freetogame_profile_url: '',
}

const MODAL_DEFAULT = {
  developer: '',
  game_url: '',
  genre: '',
  minimum_system_requirements: {
    os: '',
    processor: '',
    memory: '',
    graphics: '',
    storage: '',
  },
  publisher: '',
  release_date: '',
  short_description: '',
  thumbnail: '',
  title: '',
}

const QUANTITY_OF_CARDS = 20

const LIST_OF_CATEGORIES = [
  'mmorpg',
  'shooter',
  'strategy',
  'moba',
  'racing',
  'sports',
  'social',
  'sandbox',
  'open-world',
  'survival',
  'pvp',
  'pve',
  'pixel',
  'voxel',
  'zombie',
  'turn-based',
  'first-person',
  'third-Person',
  'top-down',
  'tank',
  'space',
  'sailing',
  'side-scroller',
  'superhero',
  'permadeath',
  'card',
  'battle-royale',
  'mmo',
  'mmofps',
  'mmotps',
  '3d',
  '2d',
  'anime',
  'fantasy',
  'sci-fi',
  'fighting',
  'action-rpg',
  'action',
  'military',
  'martial-arts',
  'flight',
  'low-spec',
  'tower-defense',
  'horror',
  'mmorts',
]

export { INFO_DEFAULT, QUANTITY_OF_CARDS, MODAL_DEFAULT, LIST_OF_CATEGORIES }
